version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:15-bullseye
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: ${PG_DATA}
    ports:
      - "5438:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
    external: true